spring.application.name=webRegister

# postgresSQL
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://dpg-cv585223esus73aq0do0-a:5432/web_register
spring.datasource.username=p
spring.datasource.password=fCtn38LbpMseY8oeOy9XbeSZkbaeYaei
spring.jpa.open-in-view=true

# DebugLevel
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

# HTTP method filter
spring.mvc.hiddenmethod.filter.enabled=true