spring.application.name=webRegister

#################################
# postgres
#################################
spring.datasource.url=jdbc:postgresql://web-register-db:5432/web-register-db
spring.datasource.username=postgres
spring.datasource.password=1218
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format-sql=true
spring.jpa.show-sql=true
#################################

# DebugLevel
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

# HTTP method filter
spring.mvc.hiddenmethod.filter.enabled=true